// <auto-generated />
namespace A2ZMOVIES.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class populateMovieGenreName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(populateMovieGenreName));
        
        string IMigrationMetadata.Id
        {
            get { return "202004222119167_populateMovieGenreName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
